version: '3.7'

services:
  api:
    container_name: api
    build:
      dockerfile: docker/dockerfiles/e2e.dockerfile
      context: ../..
    env_file:
      - ../../.env.e2e
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
    command: npm run start:e2e
    
  redis:
    container_name: redis
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
