name: Dependencies

on:
  schedule:
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Audit dependencies
        id: audit
        run: |
          echo ::set-output name=minor_dep_upgrades::$(npm run deps:lint:minor) 
          npm run deps:upgrade:minor
          npm install
          echo ::set-output name=major_dep_upgrades::$(npm run deps:lint) 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Dependency Audit"
          commit-message: "chore(deps): update dependencies to latest minor versions"
          body: |
            Minor version changes applied:
            ${{ steps.audit.outputs.minor_dep_upgrades }}
            
            Major version changes outstanding:
            ${{ steps.audit.outputs.major_dep_upgrades }}

          branch: chore/dependency-audit
